---
openapi: 3.0.0
info:
  title: Location API
  description: This Location API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://localhost:30002/
tags:
- name: locations
paths:
  /locations:
    get:
      tags:
      - locations
      description: Find location according to location id and send data to kafka
      operationId: locations
      parameters:
      - name: id
        in: query
        description: pass location id to get location
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Location'
        "400":
          description: bad input parameter
    post:
      tags:
      - locations
      description: Use rest api to send new location to gRPC-server and commit to database new location
      operationId: location
      requestBody:
        description: Location to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Location'
      responses:
        "201":
          description: location created
        "400":
          description: invalid input, object invalid
components:
  schemas:
    Location:
      required:
      - coordinate
      - creation_time
      - id
      - person_id
      type: object
      properties:
        id:
          type: integer
          example: 32
        person_id:
          type: integer
          example: 5
        creation_time:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        coordinate:
          type: string
          example: ice cream shop
