name: grpc-server - Package with Docker

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build image
        uses: docker/build-push-action@v2.7.0
        with:
          tags: tupo215/grpc-server
          file: ./modules/gRPC server/Dockerfile
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          file: ./modules/gRPC server/Dockerfile
          push: true
          tags: tupo215/grpc-server
